[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build]
target = "wasm32-unknown-unknown"

[dependencies]
gloo = "0.8.0"
web-sys = "0.3.59"
yew = "0.19.3"
yew-router = "0.16.0"
