# Use root/example as user/password credentials
version: 'v0.0.1'

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        networks:
            backend:
                ipv4_address: 127.17.0.2
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password

    web:
        build: /frontend/Dockerfile
        expose:
            - 8080
        networks:
            frontend:
                ipv4_address: 127.17.0.3

    login_serve:
        build: #TODO
        ports:
            - "3030:3030"
        networks:
            backend:
                ipv4_address: 127.17.0.4
            frontend:
                ipv4_address: 127.17.0.4
    

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
