version: 'v0.0.1'

services:
    mongo:
        image: mongo
        restart: "always"
        expose:
            - "27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password

    login_serve:
        build:
            context: login-serve
            dockerfile: Dockerfile
        expose:
            - "3030"

    web:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"
        links:
            - "login_serve"
            - "mongo"
