version: "v0.0.1"

services:
    mongo:
        image: mongo
        restart: "always"
        expose:
            - "27017"
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password

    login_serve:
        build:
            context: login-serve
            dockerfile: Dockerfile
        expose:
            - "80"
        links:
            - "mongo"
        labels:
            - "traefik.http.routers.to-login.rule=PathPrefix(`/login/request`)"

    page_serve:
        build:
            context: page-serve
            dockerfile: Dockerfile
        expose:
            - "80"
        labels:
            - "traefik.http.routers.to-page.rule=PathPrefix(`/`)"

    reverse-proxy:
        # The official v2 Traefik docker image
        image: traefik:v2.8
        # Enables the web UI and tells Traefik to listen to docker
        command: --api.insecure=true --providers.docker
        ports:
            # The HTTP port
            - "80:80"
            # The Web UI (enabled by --api.insecure=true)
            - "8080:8080"
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock
