version: 'v0.0.1'

services:
    mongo:
        image: mongo
        restart: "always"
        expose:
            - "27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password

    login_serve:
        build:
            context: login-serve
            dockerfile: Dockerfile
        expose:
            - "80"
        links:
            - "mongo"

    page_serve:
        build:
            context: page-serve
            dockerfile: Dockerfile
        expose:
            - "80"

    gateway:
        build:
            context: gateway
            dockerfile: Dockerfile
        expose:
            - "80"
        ports:
            - "80:80"
        links:
            - "page_serve"
            - "login_serve"
